theme = "mocha_custom"

[keys.insert]
"C-\\" = "normal_mode"

# [editor.file-picker]
# hidden = false

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = false
display-messages = true
auto-signature-help = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
